apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebapp
  namespace: test-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
      - image: velcsekrish/java-web-app
        name: javawebapp
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 100m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: javawebapp-service
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30002
